# Generated by Django 5.0.4 on 2024-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="django_down_excel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="检测员姓名", max_length=20)),
                ("date", models.CharField(db_column="检测日期", max_length=20)),
                ("pot", models.CharField(db_column="检测地点", max_length=20)),
                ("num", models.IntegerField(db_column="破损管道编号")),
                ("level", models.IntegerField(db_column="破损程度")),
                ("location", models.CharField(db_column="破损坐标", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_id", models.IntegerField()),
                ("account", models.IntegerField()),
                ("password", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=24)),
            ],
        ),
    ]
