# Generated by Django 5.0.4 on 2024-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="use_id", new_name="user_id",
        ),
    ]
